config/routes.rb
Rails.application.routes.draw do

  get "password_resets/new"

  get "password_resets/edit"

  root  "static_pages#home"

  get "/help",    to: "static_pages#help"

  get "/about",   to: "static_pages#about"

  get "/contact", to: "static_pages#contact"

  get "/signup",  to: "users#new"

  get "/login",   to: "sessions#new"

  post "/login",   to: "sessions#create"

  delete "/logout",  to: "sessions#destroy"

  resources :users

  resources :account_activations, only: [:edit]

  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby in Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/contact">contact page</a>
</p>

app/views/static_pages/help.html.erb
<% provide :title, t("help_page.help") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | t "base_title"</title>
  </head>
  <body>
    <h1><%= t "help_page.help"%></h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://www.railstutorial.org/help"><%= t "help_page.link_help"%></a>.
      To get help on this sample app, see the
      <a href="http://www.railstutorial.org/book"><em><%= t "link.name_book" %></em> </a> book.
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1><%= t "home.welcome_to" %></h1>
  <h2>
    <%= t "home.welcomeF" %>
    <a href="http://www.railstutorial.org/"> <%= t "link.name_book" %></a>
    <%= t "home.welcomeB" %>
  </h2>
  <%= link_to t("users.sign_up"), signup_path , class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: "Rails logo"), "http://rubyonrails.org/" %>