config/routes.rb
Rails.application.routes.draw do

  get "password_resets/new"

  get "password_resets/edit"

  root  "static_pages#home"

  get "/help",    to: "static_pages#help"

  get "/about",   to: "static_pages#about"

  get "/contact", to: "static_pages#contact"

  get "/signup",  to: "users#new"

  get "/login",   to: "sessions#new"

  post "/login",   to: "sessions#create"

  delete "/logout",  to: "sessions#destroy"

  resources :users

  resources :account_activations, only: [:edit]

  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user, only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = t "password.mail_reset"
      redirect_to root_url
    else
      flash.now[:danger] = t "password.mail_not_found"
      render "new"
    end
  end

  def edit
  end

  def update
    if params[:user][:password].empty?
      @user.errors.add :password, t("password.not_empty")
      render "edit"
    elsif @user.update_attributes(user_params)
      log_in @user
      flash[:success] = t "password.success"
      redirect_to @user
    else
      render "edit"
    end
  end

  private

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    def get_user
      @user = User.find_by(email: params[:email])
    end

    def valid_user
      unless (@user && @user.activated? && @user.authenticated?(:reset, params[:id]))
        redirect_to root_url
      end
    end

    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = t "password.password_expired"
        redirect_to new_password_reset_url
      end
    end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide :title, t("password.reset_password") %>
<h1><%= t "password.reset_password" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
      <%= render "shared/error_messages" %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, t("password.confirmation") %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit t("password.update"), class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/password_resets/new.html.erb
<% provide :title, t("password.forgot") %>
<h1><%= t "password.forgot" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>